## Some fundemental elements of programming
### Loops, tests, control flow, and functions

The core of data science is computer programming. To really explore data, we need to be able to write code to 1) wrangle data into a suitable shape for analysis and 2) do the actual analysis and visualization.

If data science didn't involve programming – if it only involved clicking buttons in a statistics program like SPSS – it would be called data science. In fact, it wouldn't even be a "thing".

What we are going to do in this tutorial is look at some of the core elements of computer programs – the things that, in fact, really make computer programs useful. We will explore these things using fairly simple examples (that will also give us practice with indexing). Later, we will see how useful these core elements are for data sience.

#### Loops

A lot of things in life are repetitive. We need to do an entire process over when only little thing has changed. For example, most of us follow the same exact routine every morning (shower/brush teeth/shave/make up/whatever) even though the only thing that has changed is one number on a calendar. The same is true for computational tasks; a teach might need to go through the exact same steps to compute a grade for each student, or a data scientist might need to go through the exact same steps to create a plot for several different but identically structured data sets.

Such repetitive tasks are very boring for humans (and bored humans tend to make more mistakes that alert humans!). While computers can't brush our teeth yet (still waiting for those tartar-eating nanobots), they can help with reapeating calculations over and over using ***loops***.

There are two kinds of loops. There are

* for loops, which run a calculation *for* a pre-determined number of times
* while loops, which run a calculation *while* some critereon is met

Let's look at these in turn.

##### for loops

Let's look at a very simple for loop and then dissect it.

In [5]:
myNewList = [1, 2, 3, 4, 5]
for i in myNewList :
    print(i)

1
2
3
4
5


The first line, `myNewList = [1, 2, 3, 4, 5]`, creates a Python list of numbers. The list in Python is a kind of ***iterable***, which is a Python object that will automatically spit out its values one-at-a-time if it's put in a for loop.

The next line, `for i in myNewList:`, sets up the for loop. It says that:

* each value in myNewList (the iterable) will be assigned to the variable `i` in turn
* every *indented* line under this line is executed with each value of `i` in turn

The third line self-explanitory; we are just printing the values of `i` to confirm that `i` is, in fact, getting assigned each value of `myNewList` in turn.

##### while loops

Sometimes we wish to repeat a calculation (or something) until some critereon is reached. For example, perhaps we need 100 samples from the the positive half of the standard normal distribution.

#### Logical Tests and Control Flow

In [19]:
x = 3
if x > 5 :
    print('big!')
else :
    print('small!')

small!


In [10]:
temp = 120
if temp >= 110 :
    print('Too hot!')
elif temp <= 85 :
    print('Too cold!')
else :
    print('Just right!')

Too hot!


In [26]:
import numpy as np
myRnds = np.random.randn(1, 5)
myRnds

array([[ 0.40551459,  2.14543361, -0.75822377,  1.88664746, -1.12765199]])

In [27]:
myRnds > 0

array([[ True,  True, False,  True, False]])

In [28]:
myRnds[myRnds > 0]

array([0.40551459, 2.14543361, 1.88664746])

#### Functions

In [29]:
def coinflip() :
    import numpy as np
    flip = np.random.randint(2) # return a random 0 or 1
    if flip == 0 :
        result = 'Tails!'
    else :
        result = 'Heads!'
    return result

coinflip()

'Tails!'

### Optional: "List Comprehension" in Python

Python itself has a cute way to make lists called *list comprehension*

#### range objects

Python has a special kind of object called a "range". It produces, on demand, range of integers without having to make a list of integers "by hand".

Let's make a range object, look at its type, and look at its contents.

In [13]:
myRange = range(10)

In [15]:
type(myRange)

range

So, note that it is *not* a list of integers, it is a "*range*". We can see this by looking at its contents:

In [17]:
print(myRange)

range(0, 10)


So, again, `myRange` is not a list of 0, 1, 2, ..., 9. Rather, it is an object that will produce these integers on demand in a for loop. 

In [18]:
# square roots of the first
roots = [] # make empty Python list
for i in myRange:
    this_root = i*i
    roots.append(this_root)
print(roots)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
